name: intellilearn
description: Offline AI Tutor
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.0
  http: ^1.2.2
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.11.0
  flutter_tts: ^4.2.0
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.4.0
  platform: ^3.1.3
  path_provider: ^2.1.5
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_textbook.pdf
